Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.16.0.0/16
        EnableDnsHostnames: true
        EnableDnsSupport: true
        Tags:
          - Name: TEST